#!/bin/bash
# Generate README.md

WORK_DIR=$(dirname $0)

README="$WORK_DIR/README.md"
echo '' > $README

GNOME_DIR="$WORK_DIR/GNOME_keybindings"
# cat $GNOME_DIR/README_API.md >> $README
cat $GNOME_DIR/README.md >> $README

cat $WORK_DIR/vimium_chrome_extension/README.md >> $README

echo '
### Tools
#### generate_readme
`generate_readme` create resulting README.md from READMEs of different parts.
' >> $README
