#!/bin/bash

WORK_DIR=$(dirname $0)

$WORK_DIR/tmux/restore

$WORK_DIR/GNOME_keybindings/restore

# git options
# git config --global user.email "shorop.d@gmail.com"
# git config --global user.name "Dmytro Shorop"
